version: '3.1'

services:
  wordpress:
    image: wordpress
    container_name: WP
    restart: always
    ports:
      - 80:80
    secrets:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    volumes:
       - wp:/var/www/html/wp-content

  db:
    image: mysql:8.0
    container_name: DB
    restart: always
    secrets:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
#      - MYSQL_RANDOM_ROOT_PASSWORD
    volumes:
      - data:/var/lib/mysql

######################################################################
# Volumes
volumes:
  data:
  wp:

######################################################################
# Redes
networks:
    defaults:
    external:
      name: wordpress

######################################################################
# Usuários e Senhas
secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_DATABASE:
    file: ./env_vars/.MYSQL_DATABASE
#  MYSQL_RAMDOM_ROOT_PASSWORD:
#    file: ./env_vars/.MYSQL_RAMDOM_ROOT_PASSWORD
  WORDPRESS_DB_HOST:
    file: ./env_vars/.WORDPRESS_DB_HOST
  WORDPRESS_DB_USER:
    file: ./env_vars/.WORDPRESS_DB_USER
  WORDPRESS_DB_PASSWORD:
    file: ./env_vars/.WORDPRESS_DB_PASSWORD
  WORDPRESS_DB_NAME:
    file: ./env_vars/.WORDPRESS_DB_NAME

